### ISSUE TITLE
Interactive editing of snake.rs does not work

### ISSUE THREAD

**Issue by Bluebird45** [PistonDevelopers/dyon#128]
The readme says: '4. Edit "source/piston_window/snake.rs" while running the demo'

I'm finding that editing snake.rs and saving while the program is running has no effect during the current run. Pressing F1 has no effect - is that meant to cause the changes to be applied?

Pressing "r" does cause the snake to begin again at the top left corner, but with the same properties (length of trail, etc) regardless of changes to the rs file. Only ending and running the program again causes the changes to apply.

**Comment by bvssvni** [comment]
Forgot to reload with the "render" module as import.

**Comment by bvssvni** [comment]
It works now.

**Comment by Bluebird45** [comment]
Thanks!
