### ISSUE TITLE
Where do these circle(..), line(..) etc functions come from

### ISSUE THREAD

**Issue by Auruss** [PistonDevelopers/dyon#161]
I'm trying to understand dyon especially the snake example. But I just don't get where these functions come from. Maybe that should be documented to be better understandable

**Comment by bvssvni** [comment]
Yes, need more documentation.

They are declared here: https://github.com/PistonDevelopers/dyon/blob/master/interactive/examples/piston_window/render.dyon

The loader imports the render module in the prelude to the snake module https://github.com/PistonDevelopers/dyon/blob/master/interactive/examples/piston_window/loader.dyon#L18.

**Comment by Auruss** [comment]
Thanks for your answer.
They seem to have different names though. Is this how named parameters work in dyon?

**Comment by bvssvni** [comment]
Yes. Named parameters are joined by `_`. See https://github.com/PistonDevelopers/dyon/issues/29. You can call them both ways.
