### ISSUE TITLE
Use closures instead of raw functions

### ISSUE THREAD

**Issue by Auruss** [PistonDevelopers/dyon#162]
I want to be able to use closures when adding functions to the module.

Use case:
I want to construct or edit a rust object that I can't store in the runtime, for example an glium vertexbuffer.
Therefore I need to access the object somehow, with raw functions it is not possible.
```

struct MyObject {
	data: Vec<NonStorable>
}

impl MyObject {
	pub fn load() -> Self {
		let vec = Vec::new()

		let mut dyon_runtime = Runtime::new();
        let mut module = Module::new();

        module.add(Arc::new("add_something".into()), || { vec.push(NotStorable::new()); }, PreludeFunction {
            lts: vec![],
            tys: vec![],
            ret: Type::Void
        });

        MyObject {
        	data: vec
        }
	}
}

```

**Comment by bvssvni** [comment]
You can use https://doc.rust-lang.org/std/thread/struct.LocalKey.html.

Or, you can use the "current" library like the interactive library currently does: https://github.com/PistonDevelopers/dyon/blob/master/interactive/examples/piston_window.rs

Alternative is to push `Variable::RustObject` to the stack. You create methods for creating the objects you need, and then call them in Dyon.

**Comment by bvssvni** [comment]
Added example for creating and reading Rust objects https://github.com/PistonDevelopers/dyon/blob/master/examples/functions.rs#L108-L121

Closing for now.
