### ISSUE TITLE
Any reason you can't publish the dyon theme for Atom on atom.io?

### ISSUE THREAD

**Issue by qolop** [PistonDevelopers/dyon#175]
Atom has a default package management tool called apm. You can easily put the theme on Atom's official site (aka where it will not only get more downloads but will be easier for other users to receive updates from.) It's very easy to do: literally just go to the folder where it is downloaded, type `apm login`, and then `apm publish patch` (for bug fixes) and `apm publish minor` for minor releases.

**Comment by qolop** [comment]
Not to mention, I followed the exact instructions for installation, and Atom doesn't detect the theme (even after restarting).

**Comment by bvssvni** [comment]
@qolop Thanks! I wanted to wait publishing until the language gets more stable. Expected bugs in the plugin as it is my first time doing this for Atom.

**Comment by bvssvni** [comment]
I've moved the plugin to its own repo and published it: https://github.com/pistondevelopers/atom-language-dyon.

Does it work now?

**Comment by qolop** [comment]
Works for me now. Thanks!
