### ISSUE TITLE
Docs, offline checking, `mod` keyword

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dyon#194]
Could use `///` like Rust does and generate markdown.

### Docs

When creating a library for a Dyon scripting environment, a `.dyon` file is kept for declaring external functions, where functions have the body `{ ... }`.

Example:

```rust
/// Prints variable to standard output.
fn println(var) { ... }
```

The docs are generated from this file, but also performs offline lifetime/type checking.

### Offline lifetime/type checking

The documentation generator could be more strict than the lifetime checker, because this is meant for sharing code, so there are additional requirements to make the code of higher quality:

- Types on all arguments and return values
- Document comments on all functions
- Declare all external functions with a `{ ... }` body (or use `mod` keyword)

### `mod` keyword

Declaring all external functions is not practical for every source file. For reusing declarations, a `mod` keyword can be used to point to a file or url.

Example:

Look for `render.dyon` in same directory.
If not found, look for `render/mod.dyon`.

```rust
mod render
```

Look for `src/lib.dyon` in the "dyon" repository.

```rust
mod "https://github.com/PistonDevelopers/dyon/"
```

*Notice! This is not used when running, only used by the offline type checker. The scripts use `load_source_imports` to avoid overhead by having dependencies loaded in memory and only accessing a single file for reloading a module.*

A file is relative to the directory which contains the `.dyon` file. `../` is allowed to go up one directory. If the file is not found, a folder with the same name and containing a `mod.dyon` can be used instead. This makes it easier to organize the code similarly to Rust.

If an url points to a Github repository, the root is `src/lib.dyon`.

When pointing to an url, the file gets downloaded and put in a `src/lib/` folder, using a glob id or hash as file name and a JSON document describing the relationships between the downloaded files and the glob id/hash.

The `src/lib/` folder is checked before downloading. This folder is relative to project directory, which is searched for by checking parents and then children using the "find_folder" library. If the `src/lib/` folder is not found, it looks in a shared folder set by an environment variable.

### Namespace and shadowing

All functions belong to the same namespace, but replacing another when shadowing.

The offline checker reports an error when calling a function is shadowed from another module.

If a function name starts with two underscores, e.g. `__foo`, the offline checker will not complain.

The order which documents are loaded is sequential from top to bottom. When a module depends on other modules, the dependencies are added before the module.

```rust
|- mod foo_dependency_1
|- mod foo_dependency_2
mod foo
|- mod bar_dependency
mod bar
```

### Motivation

The implementation of a function can vary greatly from application to application. We need a way to make sure code is reusable without loosing the flexibility of how dynamic modules are loaded.

A matching function signature makes code reusable across projects. If Alice wants to share code with Bob, but they use different engines, they can agree upon a module that defines a common interface. All code using this declaration will then be checked offline such that breaking changes can be detected.

**Comment by mrZalli** [comment]
I feel like the ability to download scripts from the internet can be a security risk. It could be used to download malicious code.

**Comment by bvssvni** [comment]
This needs some rethinking. Don't want to build a package manager for Dyon, since I think it is better to write Rust code in general when scripting is not needed.

Closing.
