### ISSUE TITLE
Tutorial for Dyon 0.8

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dyon#340]
I am working on a tutorial written for people with little programming experience.

The plan is to use Dyon 0.8 for a while to collect feedback. The tutorial will be written for 0.8 to make it easier for people to pick up the language.

When 0.9 is released, the tutorial will be updated for 0.9 and so on.

**Comment by yaskhan** [comment]
Cool! Add more OOP examples please :)

**Comment by bvssvni** [comment]
I thought it was impossible to write OOP in Dyon :P
