### ISSUE TITLE
Namespaces and external functions

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dyon#388]
Currently, all external functions in Dyon live in the same namespace. This leads to a problem when you have a Rust/Dyon library "MyLibA" using an external function `foo` and a Rust/Dyon library "MyLibB" using another function of the same name `foo`. When you try to import external functions from both MyLibA and MyLibB the two functions `foo` collides with each other.

This is not a problem when loading modules, since you can choose which module to call a function and which order one library depends on the other.

I want a way of organizing projects that works across libraries. It does not have to be a namespace in the strict sense. One project could call a function in the loader that downloads and compiles a Rust/Dyon library, and this could then be used as dependency for other modules.

**Comment by bvssvni** [comment]
Could use https://crates.io/crates/libloading

**Comment by jonysy** [comment]
> Could use https://crates.io/crates/libloading

@bvssvni Just a quick FYI: You'll likely run into problems using TLS (used [here][1], [here][2], and [here][3]) when accessing **current values** from dynamic libraries. Replacing your implementation of [current][4] with one using [lazy static][5] + [`Arc`][6] + [`Mutex`][7] is an option:

```rust
lazy_static! {
    static ref CURRENT: Arc<Mutex<HashMap<TypeId, usize>>> = ...
}
```

[1]: http://www.piston.rs/dyon-tutorial/manual-interface.html#Piston-Current
[2]: https://github.com/PistonDevelopers/current/blob/master/src/lib.rs#L16
[3]: https://github.com/PistonDevelopers/dyon/blob/master/interactive/examples/piston_window.rs#L3
[4]: https://github.com/pistondevelopers/current
[5]: https://crates.io/crates/lazy_static
[6]: https://doc.rust-lang.org/std/sync/struct.Arc.html
[7]: https://doc.rust-lang.org/std/sync/struct.Mutex.html
