### ISSUE TITLE
Make Hyper/HTTP support an optional feature

### ISSUE THREAD

**Issue by nicka101** [PistonDevelopers/dyon#442]
I would like to request you make Hyper/HTTP support an optional feature, as the language presents a good platform to use for a bunch of project ideas I have, but Hyper (thanks to OpenSSL), is difficult and unpredictable to build on Windows machines, and I think making it an optional feature would both allow for easy building on windows, and the ability to lock down a potential security hole in applications that don't need HTTP support, while also giving the developer the choice to use other HTTP libraries if they so wish (or even simply implement tighter controls on when/where HTTP is allowed).

**Comment by nicka101** [comment]
Turns out it was another crate pulling in OpenSSL, but the point still stands regarding giving the choice to the developer whether to include HTTP support

**Comment by bvssvni** [comment]
I agree. It could be moved to a separate library.

**Comment by nicka101** [comment]
Not sure its enough functionality to warrant moving it to an additional library, feature gating it should be sufficient and minimally affect users

**Comment by bvssvni** [comment]
One idea is to make HTTP support a default feature.

**Comment by nicka101** [comment]
Yeah that would work

**Comment by bvssvni** [comment]
One problem is when you want HTTP support for some part of a project while not permitting it for other parts.

**Comment by nicka101** [comment]
I think the scope of that issue is beyond that of the language itself and should probably be implemented higher up where appropriate decisions can be made based on the individual use cases (perhaps by (re)implementing the HTTP support themselves)

**Comment by nicka101** [comment]
Or alternatively, allowing intrinsics to be overriden would enable the developer to simply override HTTP support with a dummy function in areas where it should be disabled, though that would warrant a separate discussion

**Comment by bvssvni** [comment]
It is already possible to override an intrinsic, simply by declaring a new function with same name. I forgot that.
