### ISSUE TITLE
discussion - i remembered dyon whilst posting this

### ISSUE THREAD

**Issue by dobkeratops** [PistonDevelopers/dyon#460]
https://users.rust-lang.org/t/module-wide-shared-function-parameters-tls-dynamic-scope-emulation/11996

not directly related to dyon, but I remembered how dyon had 'dynamic scope' (the ability to delcare variables automatically sharable down the callgraph) .. this suggestion is sort of related.

**Comment by bvssvni** [comment]
Closing because outdated.
