### ISSUE TITLE
Tentative vim support.

### ISSUE THREAD

**Issue by thyrgle** [PistonDevelopers/dyon#508]
I recently created [vim-dyon](https://github.com/thyrgle/vim-dyon) which provides basic syntax highlighting and uses vim's `smartindent` for auto indentation. I am not particularly familiar with dyon or Vimscript so it probably isn't too polished. Not sure if you consider it polished enough to be included in the "editor plugins" section. If you want to though, feel free.

**Comment by bvssvni** [comment]
Thank you! Added: https://github.com/PistonDevelopers/dyon/blob/master/README.md

**Comment by bvssvni** [comment]
Closing.
