### ISSUE TITLE
⊻ and ⊕ for XOR

### ISSUE THREAD

**Issue by Lonami** [PistonDevelopers/dyon#539]
Earlier I read the documentation and it surprised me to see you have `∧` for `AND` and `^` for `XOR` when they look so similar. Sure, you wouldn't normally mix them, but it's funny `XOR` has no variants. `⊻` is the mathematical symbol for it. `⊕` could be another alternative. Of course, [there are more symbols](https://en.wikipedia.org/wiki/Exclusive_or) but these are the most common I believe.

**Comment by bvssvni** [comment]
I agree `⊻` would be a nice symbol for xor.

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/dyon/pull/548
