### ISSUE TITLE
dyonrun arguments

### ISSUE THREAD

**Issue by lifranc** [PistonDevelopers/dyon#542]
Dyonrun doesnt seem to be passing arguments to the script. Or is it?
Looking at the code, it seems to be only passing the first (the script to be run).
Passing over additional arguments would make it tremendously more useful.
That would allow me to use dyon instead of python/sh, and that in turn would spur me, and hopefully others, to contribute to the dyon ecosystem.
In any case, thank you for your wonderful language.

**Comment by bvssvni** [comment]
Are you looking for this? https://github.com/PistonDevelopers/dyon/blob/master/src/lib.dyon#L317

**Comment by lifranc** [comment]
Awesome! For some reason, reading dyonrun gave me the impression the remaining arguments werent' passed along! Thanks! Looking forward to a day of dyon scripting now!
