### ISSUE TITLE
Error parsing complex if-statement conditions

### ISSUE THREAD

**Issue by kaikalii** [PistonDevelopers/dyon#543]
I'm new to dyon, but I think that this code incorrectly fails to parse:
```rust
fn main() {
    x := 5
    if x > 1 && x < 6 {
        // ...
    }
}
```
The error is
```
Error #12001, Expected: `{`
2:     x := 5
3,19:     if x > 1 && x < 6 {
3,19:                   ^
```

I have found that it can be fixed by putting parenthesis around each comparison:
```rust
fn main() {
    x := 5
    if (x > 1) && (x < 6) {
        // ...
    }
}
```

Is this a bug, or is there a reason that this type of condition is not allowed?

**Comment by bvssvni** [comment]
This is intentional, to improve readability.
