### ISSUE TITLE
Process spawning

### ISSUE THREAD

**Issue by lifranc** [PistonDevelopers/dyon#550]
I and [others][1] are interested to use dyon for scripting. Rust has the `std::process::Command` interface which can spawn processes and return their output. Would you be interested to introduce this, perhaps as an optional module?

[1]: https://www.reddit.com/r/rust/comments/8ftlwo/rust_as_scripting_language/

**Comment by bvssvni** [comment]
Yeah, that would be interesting.

**Comment by lifranc** [comment]
We agree then; Make all the things rusty!
In the above-mentionned reddit, there is a reference to `duct` - [source][1]
Looks more capable than the `std::process` interface.
I'll play with it and report back.

[1]: https://docs.rs/duct/0.11.1/duct/

**Comment by lifranc** [comment]
Update; Iv begun work on a new language (written in rust of course) so I wont be contributing to dyon. Please let me add that I really enjoyed learning interesting concepts from dyon. Feel free to close or not. Thanks.
