### ISSUE TITLE
How to manipulate Current Objects from Rust?

### ISSUE THREAD

**Issue by DefecateRainbows** [PistonDevelopers/dyon#607]
Forgive me if this has already been asked somewhere, but I can see how to make a Dyon function which takes Current Object parameters, but what about Rust functions? I know you can pull values from the runtime, and sometimes that will give you the current Object that you need, but not always... I'm also aware that you have access to the current_stack like this
```rs
            let test = rt.current_stack.iter().find(|(name, _)| {
                **name == "test".to_owned()
            }).unwrap();
```
and you can use that to get the index of a current object. Should I think get the value at that index in the main stack, to get the corresponding current object? Isn't this a fairly common use case? I can't help but think that there is, hidden somewhere, a method to do this for me, or if not that there should be. What do you think about adding something like that? For now I'll just make Rust versions which take everything they need as parameters, and then make dyon wrapper functions which take the current objects for some parameters and pass those to the more verbose Rust versions.

Thank you for your time and let me know what you think about adding some helper methods like these to the runtime, to make writing Rust libraries for Dyon easier. Perhaps we could also have some for grabbing vectors with 3 elements, when you want to represent world positions or RGB colors and not quaternions or RGBA colors?

I'm willing to help however I can, let me know if you want me to write docs for these methods or even provide implementations. Your will is my command :P

**Comment by bvssvni** [comment]
I've never manipulated current objects from Rust before. There are no helper methods for this. PRs are welcome!

You should iterate in reverse direction on the current stack.

The `Vec4` type implements `From` and `Into` traits for common types, e.g. `[f32; 2]`. https://github.com/PistonDevelopers/dyon/blob/master/src/vec4.rs#L30

**Comment by DefecateRainbows** [comment]
```rs
fn current_object<T: embed::PopVariable>(rt: &mut Runtime, name: &str) -> Result<T, String> {
    let current_object_index = rt.current_stack
        .iter()
        .rev()
        .find(|(name_found, _)| **name_found == name)
        .map(|x| x.1)
        .ok_or(format!("Dyon can't find a current object with the name {}!", name))
        ?;

    T::pop_var(rt, rt.resolve(&rt.stack[current_object_index]))
}
fn teleport(rt: &mut Runtime) -> Result<(), String> {
    let test = current_object::<u32>(rt, "test")?;
    println!("Beam me up, Scotty! And you too, 7 of {}", test);
    current_object::<u32>(rt, "fail")?;
    Ok(())
}

// test Dyon:
// ~ test:= 9
// teleport()
```
Alright, this is the implementation I have! Before I clone the repo and PR, do you have any preferences for the name of the function that grabs the current object? When I try to think of what would be consistent, I realize that most of the other methods are based on `pop`, but this one is more like the `var` method. Despite this, I can't think of a way to make this name consistent with `var` in a way that makes sense.
Thanks!

**Comment by bvssvni** [comment]
Closed by https://github.com/PistonDevelopers/dyon/pull/608
