### ISSUE TITLE
Higher Order Operator Overloading

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/dyon#610]
Higher Order Operator Overloading (HOOO) is very important for higher order reasoning. For reference, see papers on path semantics notation https://github.com/advancedresearch/path_semantics/blob/master/sequences.md#notation

By adding HOOO support to Dyon, it could open up a new functional programming paradigm.
I suggest that HOOO should inline by default.

### Algebra With Closures

The syntax for "algebra with closures":

```rust
a := \(x: f64) = x + 1
b := \(x: f64) = x + 2
c := a + b
```

This is the same as:

```rust
a := \(x: f64) = x + 1
b := \(x: f64) = x + 2
c := \(x: f64) = {
    a := grab a
    b := grab b
    \a(x) + \b(x)
}
```

The above is inlined to this:

```rust
a := \(x: f64) = x + 1
b := \(x: f64) = x + 2
c := \(x: f64) = (x + 1) + (x + 2)
```

This is generalized for any binary and unary operator.

**Comment by flying-sheep** [comment]
In the “higher order calls” example, you wanted to write:

> ```rust
> a := \(x: f64) = x + 1
> b := \(x: f64) = {
>     a := grab a
>     exp(\a(x))  // missed the exp here
> }
> ```

**Comment by bvssvni** [comment]
@flying-sheep Thanks!

**Comment by bvssvni** [comment]
I believe that Higher Order Calls becomes too complicated.

- Type checking becomes messy
- Overhead when calling external functions
- Can't pass closures to external functions

**Comment by bvssvni** [comment]
I've moved Higher Order Calls to a separate issue: https://github.com/PistonDevelopers/dyon/issues/615

**Comment by bvssvni** [comment]
I believe that HOOO is too complex in Dyon and instead a language should be designed from ground up to be used with HOOO. It is more suitable for theorem proving than normal programming.

Closing.
