### ISSUE TITLE
win32:Evo-gen virus

### ISSUE THREAD

**Issue by Lightnet** [PistonDevelopers/dyon#656]
I get this virus build that it seem one or more packages are infected. This is on window 10 64bit. It stop around 

parking_lot...  /build_scipt ...

It strange that packages is infected or rogue dev. Not sure if this right to post this. Note this fresh build test.

**Comment by bvssvni** [comment]
@Lightnet Please report this here: https://github.com/Amanieu/parking_lot/issues

**Comment by Lightnet** [comment]
I see.
