### ISSUE TITLE
Disabling threading

### ISSUE THREAD

**Issue by TheNeikos** [PistonDevelopers/dyon#658]
Is there a way threading could be disabled for scripts? So that `go` does not work. I could imagine this working as a toggle on a Runtime or similarly.

**Comment by bvssvni** [comment]
Do you want this as a run-time feature, that can be turned on or off, or is it sufficient as a Cargo feature?

I assume that there would be very little overhead from having a `bool` in `Runtime`.

PRs are welcome if you want to try this out yourself.

**Comment by TheNeikos** [comment]
In my use-case it would be a cargo feature, but I am not sure how much effort that would be?

> PRs are welcome if you want to try this out yourself.

Gladly! Do you have any pointers to get started?
